using System.Windows.Forms;

namespace OP
{
    partial class fridgeOpen
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(fridgeOpen));
            back = new Button();
            buttonAdd = new Button();
            textBoxQuantity = new TextBox();
            textBoxName = new TextBox();
            panel2 = new Panel();
            button2 = new Button();
            pictureBox2 = new PictureBox();
            pictureBox1 = new PictureBox();
            button4 = new Button();
            label2 = new Label();
            textBox1 = new TextBox();
            panel3 = new Panel();
            button5 = new Button();
            pictureBox3 = new PictureBox();
            button6 = new Button();
            label3 = new Label();
            textBox2 = new TextBox();
            panel4 = new Panel();
            button7 = new Button();
            pictureBox4 = new PictureBox();
            button8 = new Button();
            label4 = new Label();
            textBox3 = new TextBox();
            panel5 = new Panel();
            panel1 = new Panel();
            button9 = new Button();
            pictureBox5 = new PictureBox();
            button10 = new Button();
            label5 = new Label();
            textBox4 = new TextBox();
            panel6 = new Panel();
            button11 = new Button();
            pictureBox6 = new PictureBox();
            button12 = new Button();
            label6 = new Label();
            textBox5 = new TextBox();
            panel7 = new Panel();
            button13 = new Button();
            pictureBox7 = new PictureBox();
            button14 = new Button();
            label7 = new Label();
            textBox6 = new TextBox();
            panel8 = new Panel();
            button15 = new Button();
            pictureBox8 = new PictureBox();
            button16 = new Button();
            label8 = new Label();
            textBox7 = new TextBox();
            panel9 = new Panel();
            button17 = new Button();
            pictureBox9 = new PictureBox();
            button18 = new Button();
            label9 = new Label();
            textBox8 = new TextBox();
            panel10 = new Panel();
            button19 = new Button();
            pictureBox10 = new PictureBox();
            button20 = new Button();
            label10 = new Label();
            textBox9 = new TextBox();
            panel11 = new Panel();
            button21 = new Button();
            pictureBox11 = new PictureBox();
            button22 = new Button();
            label11 = new Label();
            textBox10 = new TextBox();
            panel12 = new Panel();
            button23 = new Button();
            pictureBox12 = new PictureBox();
            button24 = new Button();
            label12 = new Label();
            textBox11 = new TextBox();
            panel13 = new Panel();
            button25 = new Button();
            pictureBox13 = new PictureBox();
            button26 = new Button();
            label13 = new Label();
            textBox12 = new TextBox();
            panel14 = new Panel();
            button27 = new Button();
            pictureBox14 = new PictureBox();
            button28 = new Button();
            label14 = new Label();
            textBox13 = new TextBox();
            panel15 = new Panel();
            button29 = new Button();
            pictureBox15 = new PictureBox();
            button30 = new Button();
            label15 = new Label();
            textBox14 = new TextBox();
            panel16 = new Panel();
            button31 = new Button();
            pictureBox16 = new PictureBox();
            button32 = new Button();
            label16 = new Label();
            textBox15 = new TextBox();
            panel17 = new Panel();
            button33 = new Button();
            pictureBox17 = new PictureBox();
            button34 = new Button();
            label17 = new Label();
            textBox16 = new TextBox();
            panel18 = new Panel();
            button35 = new Button();
            pictureBox18 = new PictureBox();
            button36 = new Button();
            label18 = new Label();
            textBox17 = new TextBox();
            panel19 = new Panel();
            button37 = new Button();
            pictureBox19 = new PictureBox();
            button38 = new Button();
            label19 = new Label();
            textBox18 = new TextBox();
            panel20 = new Panel();
            button39 = new Button();
            pictureBox20 = new PictureBox();
            button40 = new Button();
            label20 = new Label();
            textBox19 = new TextBox();
            panel21 = new Panel();
            button41 = new Button();
            pictureBox21 = new PictureBox();
            button42 = new Button();
            label21 = new Label();
            textBox20 = new TextBox();
            panel22 = new Panel();
            button43 = new Button();
            pictureBox22 = new PictureBox();
            button44 = new Button();
            label22 = new Label();
            textBox21 = new TextBox();
            panel23 = new Panel();
            button45 = new Button();
            pictureBox23 = new PictureBox();
            button46 = new Button();
            label23 = new Label();
            textBox22 = new TextBox();
            panel24 = new Panel();
            button47 = new Button();
            pictureBox24 = new PictureBox();
            button48 = new Button();
            label24 = new Label();
            textBox23 = new TextBox();
            panel25 = new Panel();
            button49 = new Button();
            pictureBox25 = new PictureBox();
            button50 = new Button();
            label25 = new Label();
            textBox24 = new TextBox();
            panel26 = new Panel();
            button51 = new Button();
            pictureBox26 = new PictureBox();
            button52 = new Button();
            label26 = new Label();
            textBox25 = new TextBox();
            panel27 = new Panel();
            button53 = new Button();
            pictureBox27 = new PictureBox();
            button54 = new Button();
            label27 = new Label();
            textBox26 = new TextBox();
            panel28 = new Panel();
            button55 = new Button();
            pictureBox28 = new PictureBox();
            button56 = new Button();
            label28 = new Label();
            textBox27 = new TextBox();
            panel29 = new Panel();
            button57 = new Button();
            pictureBox29 = new PictureBox();
            button58 = new Button();
            label29 = new Label();
            textBox28 = new TextBox();
            panel30 = new Panel();
            button59 = new Button();
            pictureBox30 = new PictureBox();
            button60 = new Button();
            label30 = new Label();
            textBox29 = new TextBox();
            panel31 = new Panel();
            button61 = new Button();
            pictureBox31 = new PictureBox();
            button62 = new Button();
            label31 = new Label();
            textBox30 = new TextBox();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            panel1.SuspendLayout();
            panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox2).BeginInit();
            panel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox3).BeginInit();
            panel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox4).BeginInit();
            panel5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox5).BeginInit();
            panel6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox6).BeginInit();
            panel7.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox7).BeginInit();
            panel8.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox8).BeginInit();
            panel9.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox9).BeginInit();
            panel10.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox10).BeginInit();
            panel11.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox11).BeginInit();
            panel12.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox12).BeginInit();
            panel13.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox13).BeginInit();
            panel14.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox14).BeginInit();
            panel15.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox15).BeginInit();
            panel16.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox16).BeginInit();
            panel17.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox17).BeginInit();
            panel18.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox18).BeginInit();
            panel19.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox19).BeginInit();
            panel20.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox20).BeginInit();
            panel21.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox21).BeginInit();
            panel22.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox22).BeginInit();
            panel23.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox23).BeginInit();
            panel24.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox24).BeginInit();
            panel25.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox25).BeginInit();
            panel26.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox26).BeginInit();
            panel27.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox27).BeginInit();
            panel28.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox28).BeginInit();
            panel29.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox29).BeginInit();
            panel30.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox30).BeginInit();
            panel31.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox31).BeginInit();
            SuspendLayout();
            // 
            // back
            // 
            back.BackColor = SystemColors.ButtonFace;
            back.Cursor = Cursors.Hand;
            back.FlatAppearance.BorderColor = Color.IndianRed;
            back.FlatStyle = FlatStyle.Flat;
            back.Font = new Font("Sitka Small", 7.8F, FontStyle.Bold, GraphicsUnit.Point, 204);
            back.Location = new Point(915, 12);
            back.Name = "back";
            back.Size = new Size(99, 39);
            back.TabIndex = 13;
            back.Text = "Назад";
            back.UseVisualStyleBackColor = false;
            back.Click += back_Click;
            back.MouseDown += back_MouseDown;
            back.MouseUp += back_MouseUp;
            // 
            // buttonAdd
            // 
            buttonAdd.Location = new Point(44, 168);
            buttonAdd.Name = "buttonAdd";
            buttonAdd.Size = new Size(94, 29);
            buttonAdd.TabIndex = 14;
            buttonAdd.Text = "Додати";
            buttonAdd.UseVisualStyleBackColor = true;
            buttonAdd.Click += buttonAdd_Click;
            // 
            // textBoxQuantity
            // 
            textBoxQuantity.Location = new Point(44, 100);
            textBoxQuantity.Multiline = true;
            textBoxQuantity.Name = "textBoxQuantity";
            textBoxQuantity.Size = new Size(178, 41);
            textBoxQuantity.TabIndex = 15;
            // 
            // textBoxName
            // 
            textBoxName.Location = new Point(44, 43);
            textBoxName.Multiline = true;
            textBoxName.Name = "textBoxName";
            textBoxName.Size = new Size(178, 41);
            textBoxName.TabIndex = 16;
            // 
            // fridgeOpen
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackgroundImage = (Image)resources.GetObject("$this.BackgroundImage");
            ClientSize = new Size(1133, 725);
            Controls.Add(panel31);
            Controls.Add(panel30);
            Controls.Add(panel29);
            Controls.Add(panel28);
            Controls.Add(panel27);
            Controls.Add(panel26);
            Controls.Add(panel25);
            Controls.Add(panel24);
            Controls.Add(panel23);
            Controls.Add(panel22);
            Controls.Add(panel21);
            Controls.Add(panel20);
            Controls.Add(panel19);
            Controls.Add(panel18);
            Controls.Add(panel17);
            Controls.Add(panel16);
            Controls.Add(panel15);
            Controls.Add(panel14);
            Controls.Add(panel13);
            Controls.Add(panel12);
            Controls.Add(panel11);
            Controls.Add(panel10);
            Controls.Add(panel9);
            Controls.Add(panel8);
            Controls.Add(panel7);
            Controls.Add(panel6);
            Controls.Add(panel5);
            Controls.Add(panel4);
            Controls.Add(panel3);
            Controls.Add(panel2);
            Controls.Add(panel1);
            Controls.Add(textBoxName);
            Controls.Add(textBoxQuantity);
            Controls.Add(buttonAdd);
            Controls.Add(back);
            FormBorderStyle = FormBorderStyle.None;
            Name = "fridgeOpen";
            Text = "Form1";
            MouseDown += fridgeOpen_MouseDown;
            MouseMove += fridgeOpen_MouseMove;
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            panel2.ResumeLayout(false);
            panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox2).EndInit();
            panel3.ResumeLayout(false);
            panel3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox3).EndInit();
            panel4.ResumeLayout(false);
            panel4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox4).EndInit();
            panel5.ResumeLayout(false);
            panel5.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox5).EndInit();
            panel6.ResumeLayout(false);
            panel6.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox6).EndInit();
            panel7.ResumeLayout(false);
            panel7.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox7).EndInit();
            panel8.ResumeLayout(false);
            panel8.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox8).EndInit();
            panel9.ResumeLayout(false);
            panel9.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox9).EndInit();
            panel10.ResumeLayout(false);
            panel10.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox10).EndInit();
            panel11.ResumeLayout(false);
            panel11.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox11).EndInit();
            panel12.ResumeLayout(false);
            panel12.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox12).EndInit();
            panel13.ResumeLayout(false);
            panel13.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox13).EndInit();
            panel14.ResumeLayout(false);
            panel14.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox14).EndInit();
            panel15.ResumeLayout(false);
            panel15.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox15).EndInit();
            panel16.ResumeLayout(false);
            panel16.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox16).EndInit();
            panel17.ResumeLayout(false);
            panel17.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox17).EndInit();
            panel18.ResumeLayout(false);
            panel18.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox18).EndInit();
            panel19.ResumeLayout(false);
            panel19.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox19).EndInit();
            panel20.ResumeLayout(false);
            panel20.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox20).EndInit();
            panel21.ResumeLayout(false);
            panel21.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox21).EndInit();
            panel22.ResumeLayout(false);
            panel22.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox22).EndInit();
            panel23.ResumeLayout(false);
            panel23.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox23).EndInit();
            panel24.ResumeLayout(false);
            panel24.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox24).EndInit();
            panel25.ResumeLayout(false);
            panel25.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox25).EndInit();
            panel26.ResumeLayout(false);
            panel26.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox26).EndInit();
            panel27.ResumeLayout(false);
            panel27.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox27).EndInit();
            panel28.ResumeLayout(false);
            panel28.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox28).EndInit();
            panel29.ResumeLayout(false);
            panel29.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox29).EndInit();
            panel30.ResumeLayout(false);
            panel30.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox30).EndInit();
            panel31.ResumeLayout(false);
            panel31.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox31).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private Button back;
        private Button buttonAdd;
        private TextBox textBoxQuantity;
        private TextBox textBoxName;
        private Panel panel2;
        private Button button2;
        private PictureBox pictureBox2;
        private Button button4;
        private Label label2;
        private TextBox textBox1;
        private Panel panel3;
        private Button button5;
        private PictureBox pictureBox3;
        private PictureBox pictureBox1;
        private Button button6;
        private Label label3;
        private TextBox textBox2;
        private Panel panel4;
        private Button button7;
        private PictureBox pictureBox4;
        private Button button8;
        private Label label4;
        private TextBox textBox3;
        private Panel panel5;
        private Button button9;
        private PictureBox pictureBox5;
        private Button button10;
        private Label label5;
        private TextBox textBox4;
        private Panel panel6;
        private Button button11;
        private PictureBox pictureBox6;
        private Button button12;
        private Label label6;
        private TextBox textBox5;
        private Panel panel7;
        private Panel panel1;
        private Button button13;
        private PictureBox pictureBox7;
        private Button button14;
        private Label label7;
        private TextBox textBox6;
        private Panel panel8;
        private Button button15;
        private PictureBox pictureBox8;
        private Button button16;
        private Label label8;
        private TextBox textBox7;
        private Panel panel9;
        private Button button17;
        private PictureBox pictureBox9;
        private Button button18;
        private Label label9;
        private TextBox textBox8;
        private Panel panel10;
        private Button button19;
        private PictureBox pictureBox10;
        private Button button20;
        private Label label10;
        private TextBox textBox9;
        private Panel panel11;
        private Button button21;
        private PictureBox pictureBox11;
        private Button button22;
        private Label label11;
        private TextBox textBox10;
        private Panel panel12;
        private Button button23;
        private PictureBox pictureBox12;
        private Button button24;
        private Label label12;
        private TextBox textBox11;
        private Panel panel13;
        private Button button25;
        private PictureBox pictureBox13;
        private Button button26;
        private Label label13;
        private TextBox textBox12;
        private Panel panel14;
        private Button button27;
        private PictureBox pictureBox14;
        private Button button28;
        private Label label14;
        private TextBox textBox13;
        private Panel panel15;
        private Button button29;
        private PictureBox pictureBox15;
        private Button button30;
        private Label label15;
        private TextBox textBox14;
        private Panel panel16;
        private Button button31;
        private PictureBox pictureBox16;
        private Button button32;
        private Label label16;
        private TextBox textBox15;
        private Panel panel17;
        private Button button33;
        private PictureBox pictureBox17;
        private Button button34;
        private Label label17;
        private TextBox textBox16;
        private Panel panel18;
        private Button button35;
        private PictureBox pictureBox18;
        private Button button36;
        private Label label18;
        private TextBox textBox17;
        private Panel panel19;
        private Button button37;
        private PictureBox pictureBox19;
        private Button button38;
        private Label label19;
        private TextBox textBox18;
        private Panel panel20;
        private Button button39;
        private PictureBox pictureBox20;
        private Button button40;
        private Label label20;
        private TextBox textBox19;
        private Panel panel21;
        private Button button41;
        private PictureBox pictureBox21;
        private Button button42;
        private Label label21;
        private TextBox textBox20;
        private Panel panel22;
        private Button button43;
        private PictureBox pictureBox22;
        private Button button44;
        private Label label22;
        private TextBox textBox21;
        private Panel panel23;
        private Button button45;
        private PictureBox pictureBox23;
        private Button button46;
        private Label label23;
        private TextBox textBox22;
        private Panel panel24;
        private Button button47;
        private PictureBox pictureBox24;
        private Button button48;
        private Label label24;
        private TextBox textBox23;
        private Panel panel25;
        private Button button49;
        private PictureBox pictureBox25;
        private Button button50;
        private Label label25;
        private TextBox textBox24;
        private Panel panel26;
        private Button button51;
        private PictureBox pictureBox26;
        private Button button52;
        private Label label26;
        private TextBox textBox25;
        private Panel panel27;
        private Button button53;
        private PictureBox pictureBox27;
        private Button button54;
        private Label label27;
        private TextBox textBox26;
        private Panel panel28;
        private Button button55;
        private PictureBox pictureBox28;
        private Button button56;
        private Label label28;
        private TextBox textBox27;
        private Panel panel29;
        private Button button57;
        private PictureBox pictureBox29;
        private Button button58;
        private Label label29;
        private TextBox textBox28;
        private Panel panel30;
        private Button button59;
        private PictureBox pictureBox30;
        private Button button60;
        private Label label30;
        private TextBox textBox29;
        private Panel panel31;
        private Button button61;
        private PictureBox pictureBox31;
        private Button button62;
        private Label label31;
        private TextBox textBox30;
    }
}